# Generated by Django 4.2.7 on 2024-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressalle',
            name='statut',
            field=models.CharField(choices=[('Confirmer', 'Confirmer'), ('Annuler', 'Annuler'), ('Ajourné', 'Ajourné'), ('Reporter', 'Reporter'), ('Prolonger', 'Prolonger'), ('EnAttente', 'En Attente')], max_length=100),
        ),
    ]
