# Generated by Django 4.2.7 on 2024-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0002_alter_ressalle_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codefacture', models.CharField(max_length=50)),
                ('etablissement', models.CharField(max_length=100)),
                ('demandeur', models.CharField(max_length=100)),
                ('courrier', models.EmailField(max_length=254)),
                ('dateEntree', models.DateField()),
                ('dateSortie', models.DateField()),
            ],
        ),
    ]
