# Generated by Django 4.2.7 on 2024-06-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0003_facture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='dateEntree',
            new_name='dateEntrée',
        ),
        migrations.AlterField(
            model_name='facture',
            name='courrier',
            field=models.IntegerField(),
        ),
    ]
