# Generated by Django 4.2.7 on 2024-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0005_alter_facture_courrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='courrier',
            field=models.PositiveIntegerField(),
        ),
    ]
