# Generated by Django 4.2.7 on 2024-06-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0006_alter_facture_courrier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restauration',
        ),
    ]
