# Generated by Django 4.2.7 on 2024-06-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0007_delete_restauration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=45)),
                ('prenom', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=45)),
                ('capacite', models.PositiveIntegerField()),
                ('chambredispo', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
